name: Alta de Usuario

on:
  workflow_dispatch:
    inputs:
      email:
        description: "Correo del nuevo usuario"
        required: true
        type: string
      rol:
        description: "Rol del usuario (lider_tecnico o developer)"
        required: true
        type: choice
        options:
          - lider_tecnico
          - developer

jobs:
  add-user:
    runs-on: ubuntu-latest

    steps:
      - name: Definir Team ID según rol
        id: set_team
        run: |
          if [ "${{ github.event.inputs.rol }}" = "lider_tecnico" ]; then
            echo "TEAM_ID=xxx" >> $GITHUB_ENV
          elif [ "${{ github.event.inputs.rol }}" = "developer" ]; then
            echo "TEAM_ID=yyyy" >> $GITHUB_ENV
          else
            echo "Rol no válido"
            exit 1
          fi

      - name: Invitar usuario vía API de GitHub
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.ORG_ADMIN_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/orgs/${{ github.repository_owner }}/invitations \
            -d "{\"email\":\"${{ github.event.inputs.email }}\",\"role\":\"direct_member\",\"team_ids\":[${{ env.TEAM_ID }}]}"
