name: Baja de Usuario

on:
  workflow_dispatch:
    inputs:
      username:
        description: "Username de GitHub del usuario a eliminar de la organización"
        required: true
        type: string

jobs:
  remove-user:
    runs-on: ubuntu-latest

    steps:
      - name: Remover usuario de la organización
        run: |
          curl -L \
            -X DELETE \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.ORG_ADMIN_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/orgs/${{ github.repository_owner }}/members/${{ github.event.inputs.username }}
